import Head from "next/head";
import styles from "../styles/Page2.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Page 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <center>
          <div>Welcome to page 2</div>
        </center>
      </main>
    </>
  );
}
